name: smartpy-base

dependencies:
  - python=3.8.2
  - boto
  - boto3
  - botocore
  - s3fs
  - pandas
  - pip
  - numpy
  - matplotlib
  - mysql-connector-python
  - mysqlclient
  - sqlalchemy
  - psutil
  - scikit-learn
  - pip:
    - awswrangler
    - snscrape
    - twitter_data
    - edlib
    - nltk
    - python-binance
    - setuptools
